# Generated by Django 3.2.6 on 2024-04-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historywedding',
            name='preview_small',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d/small/'),
        ),
    ]
