# Generated by Django 3.2.6 on 2024-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_historywedding_preview_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='historywedding',
            name='slug',
            field=models.SlugField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historywedding',
            name='intro',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='historywedding',
            name='preview_small',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
