# Generated by Django 3.2.6 on 2024-04-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20240401_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historywedding',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='historywedding',
            name='intro',
            field=models.TextField(max_length=500, verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='historywedding',
            name='preview',
            field=models.ImageField(upload_to='image/%y/%m/%d/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='historywedding',
            name='preview_small',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Маленькое изображение'),
        ),
        migrations.AlterField(
            model_name='historywedding',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='historywedding',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%y/%m/%d/', verbose_name='Изображения')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.historywedding', verbose_name='Истории')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
