# Generated by Django 3.2.6 on 2024-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20240402_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='image_main/')),
                ('text_portfolio', models.TextField(max_length=400, verbose_name='Текст портфолио')),
                ('text_about', models.TextField(max_length=400, verbose_name='Текст обо мне')),
            ],
            options={
                'verbose_name': 'настройки сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
        migrations.AlterModelOptions(
            name='historywedding',
            options={'verbose_name': 'Историю', 'verbose_name_plural': 'Истории'},
        ),
    ]
