# Generated by Django 3.2.6 on 2024-04-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20240402_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='text_contact',
            field=models.TextField(default=1, max_length=400, verbose_name='Текст контактов'),
            preserve_default=False,
        ),
    ]
