# Generated by Django 3.2.6 on 2024-04-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_sitesettings_text_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='link_contact',
            field=models.CharField(default=1, max_length=100, verbose_name='Ссылка контактов'),
            preserve_default=False,
        ),
    ]
